- images/web/config/production.conf
> Set timeout for apache config

- .github/workflows/chartpress.yaml
- images/tiler-server/seed-by-diffs.sh
- ohm/requirements.yaml
- values.production.template.yaml
- values.staging.template.yaml
Deploy https://github.com/developmentseed/osm-seed/pull/194 to resume tiler updates.
> Fix tiler updates

- values.production.template.yaml
> switch to bigger ebs volumne. adjust imposm sequence number

- .github/workflows/chartpress.yaml
- ohm/requirements.yaml
- values.production.template.yaml
> Kubernetes updates from v1.15 - v.16

- .github/workflows/chartpress.yaml
Fixes for timeslider not loading twice when page.load is called by some other element on the page.
> Deploy timeslider load fixes

- images/tiler-server/config/config.toml
> Fix id field name for transport associated streets

- .github/workflows/chartpress.yaml
- images/web/Dockerfile
- images/web/start.sh
- ohm/requirements.yaml
- values.production.template.yaml
- values.staging.template.yaml
Adding a New Relic APM configuration in order to track clients interactions  https://github.com/OpenHistoricalMap/issues/issues/285
@danrademacher @geohacker
> New Relic configuration

- values.production.template.yaml
> Set full-history  replication in production

- .github/workflows/chartpress.yaml
> Fix awscli instalation

- ohm/requirements.yaml
- values.staging.template.yaml
> Fix API DB backup creation

- ohm/requirements.yaml
- values.production.template.yaml
- values.staging.template.yaml
> Set ohm-api and ohm-overpass-api for nominatim

- values.staging.template.yaml
> Update staging pod labels in order to select nodes

- ohm/requirements.yaml
- values.staging.template.yaml
Feature Request from : https://github.com/OpenHistoricalMap/issues/issues/271
I made some fixes on staging, it works fine: 
https://vtiles-staging.openhistoricalmap.org/#22/50.08738675/14.42134769
cc. @geohacker @batpad
> Add artwork_type feature to other_points layer - production

- images/tiler-server/config/config.toml
> Add site_type in other_points layer - vtiles

- images/tiler-server/config/config.toml
From https://github.com/OpenHistoricalMap/issues/issues/274
cc. @tsinn
> Add bridge feature for water_lines layer

- images/tiler-server/config/config.toml
This brings in production vs staging sprite, and also updates `git://` to `https://` in vendorfile
> Update production from staging

- images/tiler-server/seed-by-diffs.sh
- images/tiler-server/tile_cache_downloader.sh
- images/web/Dockerfile
- Reducing number of logs for tiler cache cleaner
-  Woodblock style updates
cc. @danrademacher
> Pushing staging changes to production

- ohm/requirements.yaml
- values.staging.template.yaml
> Update osm-seed helm charts

- images/tiler-server/Dockerfile
- images/tiler-server/config/config.toml
- ohm/requirements.yaml
- values.production.template.yaml
- values.staging.template.yaml
From: https://github.com/OpenHistoricalMap/issues/issues/343#issuecomment-1068033301
cc. @tsinn @batpad
> Update osm-seed version for tiler

- images/tiler-server/config/config.toml
From https://github.com/OpenHistoricalMap/issues/issues/348
cc. @batpad
> Display all types of railway at same zoom level in VT

- images/taginfo/taginfo-config-production.json
Fix for https://github.com/OpenHistoricalMap/issues/issues/342
cc @danrademacher @Rub21
> fix overpass turbo link for taginfo

- images/tasking-manager-api/Dockerfile
update commit hash for tasking manager fork
cc @willemarcel
> update tm commit

- .github/workflows/chartpress.yaml
- ohm/requirements.yaml
- values.production.template.yaml
- values.staging.template.yaml
> Update osm-seed Version

- ohm/requirements.yaml
- values.staging.template.yaml
> Update domain configuration 

- images/tiler-server/config/config.toml
From: https://github.com/OpenHistoricalMap/issues/issues/384#issuecomment-1163415456
cc. @batpad @tsinn
> Add wetland type in VT

- images/web/Dockerfile
for https://github.com/OpenHistoricalMap/issues/issues/388
> Restore vendorer to dockerfile

- images/web/Dockerfile
for https://github.com/OpenHistoricalMap/issues/issues/382
> update minor content, en-GB file

- ohm/requirements.yaml
Refs https://github.com/OpenHistoricalMap/issues/issues/420
cc @Rub21 @geohacker
> update osm-seed version to include fixes to env names

- images/web/start.sh
Trying to write id key and memcache directly in the settings.yml
> add id key and memcache servers in settings.yml

- ohm/requirements.yaml
> Update osm-seed version - Taginfo

- values.production.template.yaml
> Set latest planet replicacion for overpass

- images/web/Dockerfile
- values.production.template.yaml
- values.staging.template.yaml
> Set 2 replicas for web container

- ohm/requirements.yaml
- values.production.template.yaml
- values.staging.template.yaml
from : https://github.com/OpenHistoricalMap/issues/issues/425
> Fixing  Overpass  for updating database from replication files

- images/tiler-server/config/config.toml
From https://github.com/OpenHistoricalMap/issues/issues/385
cc. @tsinn  @danrademacher
> Add natural=cliff in VT

- values.production.template.yaml
> Update tiler replication input values - production

- values.production.template.yaml
cc. @batpad @jeffreyameyer @danrademacher @geohacker
> Increase production Tasking Manager pods=2

- .github/workflows/chartpress.yaml
- images/tiler-server/config/config.toml
from : https://github.com/OpenHistoricalMap/issues/issues/487
cc. @batpad @tsinn
> Add construction for highways in tiler

- ohm/requirements.yaml
- values.production.template.yaml
- values.staging.template.yaml
- oms-seed version updates to take changes to import landuse_lines.
- Update Latest replication planet files for tiles and nominatim.
> Update osm-seed version and values for planet replication files

- values.production.template.yaml
- values.staging.template.yaml
Because of https://github.com/OpenHistoricalMap/issues/issues/477#issuecomment-1404320797, I am updating the new nominatim API urls for staging and production.
cc @danrademacher @batpad @geohacker
> Update Nominatim API url

- values.production.template.yaml
- values.staging.template.yaml
> Update planet replication file for nominatim

- .github/workflows/frontend-tasking-manager.yaml
- docs/tm-consumer-keys.md
- images/web/Dockerfile
- images/web/config/production.conf
- images/web/config/settings.yml
- images/web/start.sh
- ohm/requirements.yaml
- values.staging.template.yaml
- Deploy upstream website
- Add github action to deploy TM frontend
- Minor changes for replication container., basically add `set -e` 
cc. @danrademacher @geohacker @batpad
> Deploy upstream website - Production

- images/tiler-server/config/config.toml
- images/web/Dockerfile
- Set landuse_points >= 6 for vtiles
- Update website with new vtiles styles
> Update website styles

- images/tiler-server/config/config.toml
cc. @danrademacher @tsinn @batpad
> Update water_areas for tiler

- values.production.template.yaml
> Fix tiler db label

- values.production.template.yaml
> Set false nodeSelector for Imposm and tiler-cache

- values.production.template.yaml
> Update replication sequence for tiler production

- ohm/requirements.yaml
- values.production.template.yaml
- values.staging.template.yaml
> Minute replication monitoring

- images/tiler-server/cache_cleaner.sh
- images/web/config/cgimap.conf
- images/web/config/production.conf
- ohm/requirements.yaml
- values.production.template.yaml
- values.staging.template.yaml
From https://github.com/OpenHistoricalMap/issues/issues/588
- Adding LimitRequestBody in web apache config
- Remove tiles cache cleaner script that delete tegola process 
-  Add changeset Replication Job container
cc. @batpad
> Updates for production

- images/tiler-server/cache_cleaner.sh
- images/tiler-server/seed-by-diffs.sh
- images/web/config/settings.yml
- ohm/requirements.yaml
- values.production.template.yaml
- values.staging.template.yaml
> Set temporal s3 cleaning for tiler and increase max_number_of_nodes in api

- images/web/Dockerfile
> Update ohm website

- .github/workflows/frontend-tasking-manager.yaml
From: https://github.com/OpenHistoricalMap/issues/issues/605#issuecomment-1719785159
cc. @danrademacher @1ec5 @batpad
> Update OSM_SERVER_URL for production

- .github/workflows/frontend-tasking-manager.yaml
> Update to www the TM api config

- .github/workflows/frontend-tasking-manager.yaml
cc @Rub21 you had an extra W in the URL. I suspect it's been a LONG day
> Remove extra w from www in OSM_SERVER_URL

- .github/workflows/chartpress.yaml
- images/web/config/production.conf
- ohm/requirements.yaml
- values.production.template.yaml
- values.staging.template.yaml
- Update website for upstream catchup
- Osmcha configs that are not going to apply in production yet.
> Staging updates to Production

- ohm/requirements.yaml
> Set node selector for backups jobs

- images/web/config/production.conf
> Enable CGIMAP Apache  redirects for uploads

- values.production.template.yaml
> Add sharedMemorySize for db - prod

- images/web/start.sh
From: https://github.com/zerebubuth/openstreetmap-cgimap/issues/330
cc. @batpad @1ec5 @danrademacher @mmd-osm
> Enable daemon mode for cgimap

- values.production.template.yaml
- values.staging.template.yaml
cc. @batpad @willemarcel @danrademacher
> OSMCHA producion

- README.md
- images/web/Dockerfile
- ohm/requirements.yaml
- values.production.template.yaml
- values.staging.template.yaml
cc. @batpad @danrademacher @1ec5
> Overpass version upgrade

- ohm/requirements.yaml
- values.staging.template.yaml
cc. @batpad @danrademacher @jeffreyameyer
> Fix taginfo container

- values.production.template.yaml
cc. @jeffreyameyer @danrademacher @batpad
> Increase cpu and memory for web container - production

- images/web/Dockerfile
Deploy on request from @jeffreyameyer to get a map style change in place before Friday demo
> pull in latest map atyle

- values.production.template.yaml
cc. @batpad @danrademacher @jeffreyameyer
> Update values from latest replication files for tiler

- values.production.template.yaml
cc. @batpad @jeffreyameyer @danrademacher
> Re-import planet  data in tiler production

- values.production.template.yaml
> Update EBS id for tiler - prod

- ohm/requirements.yaml
From: https://github.com/OpenHistoricalMap/issues/issues/682#issuecomment-1928846973 and https://github.com/OpenHistoricalMap/issues/issues/692 
The issue has been fixed in staging! https://osmcha-staging.openhistoricalmap.org/
cc @danrademacher @batpad
> Update osmcha frontend version

- images/web/Dockerfile
for https://github.com/OpenHistoricalMap/issues/issues/405
> Add new rail style

- ohm/requirements.yaml
- values.production.template.yaml
* Rail style
* Help updates
* Latest translations
> Staging deploy latest web changes

- ohm/requirements.yaml
- values.production.template.yaml
- values.staging.template.yaml
- Update the imposm process to automatically restart using the latest updates obtained from minute replications.
- Add live livenessProbe in imposm to check the process and restart the container if the process get stuck
> Update imposm process

- .gitignore
- compose/tiler.yml
- compose/web.yml
- envs/.env.tiler.example
- envs/.env.web.example
- images/tiler-server/Dockerfile
- images/tiler-server/config/config.toml
From: https://github.com/OpenHistoricalMap/issues/issues/702
> Tiler simplification for admin levels

- images/tiler-server/config/config.toml
> Simplifying coastlines

- images/web/Dockerfile
Restore place points to main map style. Let's wrap this into next week's deploy if possible
> Update website commit hash

- images/tiler-server/config/config.template.toml
- images/tiler-server/config/providers/transport_areas.toml
- images/tiler-server/config/providers/transport_lines.toml
- images/tiler-server/config/providers/transport_points.toml
- ohm/requirements.yaml
- values.staging.template.yaml
From: https://github.com/OpenHistoricalMap/issues/issues/664
@danrademacher
> Add service tags for gen0 and gen1 - tiler

- images/taginfo/taginfo-config-production.json
- images/taginfo/taginfo-config-staging.json
- ohm/requirements.yaml
- values.production.template.yaml
- values.staging.template.yaml
from: https://github.com/OpenHistoricalMap/issues/issues/738
> Taginfo updates

- values.production.template.yaml
> Deploy tiler-db using new values and EBS

- compose/web.yml
- images/db/Dockerfile
- values.staging.template.yaml
> DB upgrade to Postgres 14

- images/web/config/settings.yml
> Set the site to read_only - production

- images/web/config/settings.local.yml
From https://github.com/OpenHistoricalMap/issues/issues/779
> Update settings.local.yml file

- .github/workflows/chartpress.yaml
- chartpress.yaml
From https://github.com/OpenHistoricalMap/issues/issues/782
Images are been store here: https://github.com/orgs/OpenHistoricalMap/packages
cc . @batpad @danrademacher
> Using GitHub contianer registry to store docker images 

- .github/workflows/chartpress.yaml
- .gitignore
- chartpress.yaml
- compose/tiler.yml
- images/tiler-imposm/Dockerfile
- images/tiler-imposm/README.md
- images/tiler-imposm/config/imposm3.json
- images/tiler-imposm/config/postgis_helpers.sql
- images/tiler-imposm/config/postgis_index.sql
- images/tiler-imposm/config/postgis_post_import.sql
- images/tiler-imposm/liveness.sh
- images/tiler-imposm/scripts/natural_earth.sh
- images/tiler-imposm/scripts/osm_land.sh
- images/tiler-imposm/start.sh
- ohm/values.yaml
- values.staging.template.yaml
From: https://github.com/OpenHistoricalMap/issues/issues/701#issuecomment-2100873073
> Add Tiler imposm

- images/tiler-server/config/config.template.toml
- images/tiler-server/config/providers/water_areas_ne.toml
From https://github.com/OpenHistoricalMap/issues/issues/794
> Update Natural Earth water body zoom level

- images/tiler-server/config/config.template.toml
- images/tiler-server/config/providers/water_areas_ne.toml
From https://github.com/OpenHistoricalMap/issues/issues/794#issuecomment-2135499084
> Update TOM files for tiler - natural earth

- images/web/Dockerfile
Includes changes for https://github.com/OpenHistoricalMap/issues/issues/787
> Pull in latest map style

- images/web/Dockerfile
This is for https://github.com/OpenHistoricalMap/issues/issues/792 and combines map style updates and improvements in naming and deployment
> Map style deploy

- .github/workflows/frontend-overpass.yaml
see https://github.com/OpenHistoricalMap/issues/issues/792
> Fix overpass turbo map style name

- values.production.template.yaml
> Update Overpass values for production

- ohm/requirements.yaml
From: https://github.com/OpenHistoricalMap/issues/issues/718
cc. @erictheise @1ec5
> Update  Overpass version

- .github/workflows/frontend-overpass.yaml
- ohm/requirements.yaml
> Update osm-seed and overpass version

- .github/workflows/chartpress.yaml
- images/web/Dockerfile
cc. @danrademacher @jeffreyameyer
> Update version of CGIMap

- images/db/config/postgresql.production.conf
- values.production.template.yaml
> Update values for production api db

- values.production.template.yaml
cc. @jeffreyameyer @danrademacher @batpad
> Set OHM site to api_readonly

- values.production.template.yaml
From: https://github.com/OpenHistoricalMap/issues/issues/575#issuecomment-2227420172
> Update values for overpass api

- images/web/config/production.conf
- values.production.template.yaml
From: https://github.com/OpenHistoricalMap/issues/issues/850
cc. @batpad @jeffreyameyer
> Increase proxy timeout for apache and update resources for api web container 

- images/web/Dockerfile
> Update Dockerfile with new map-style commit

- images/web/cgimap.sh
> Update cgimap config

- .github/workflows/frontend-tasking-manager.yaml
- images/tasking-manager-api/Dockerfile
- images/tiler-imposm/config/postgis_index.sql
- images/tiler-server/config/config.template.toml
- images/tiler-server/config/providers/place_points.toml
- images/tiler-server/config/providers/place_points.zoom.toml
- images/tiler-server/config/providers/transport_lines.toml
- images/tiler-server/config/providers/transport_lines.zoom.toml
- images/tiler-server/config/providers/water_lines.toml
- images/tiler-server/config/providers/water_lines.zoom.toml
- images/web/Dockerfile
- images/web/cgimap.sh
- values.production.template.yaml
- values.staging.template.yaml
It would be great to get these new translations out this week.
> v2.0.3 release; translations-only.

- images/tiler-server/config/providers/transport_lines.toml
From: https://github.com/OpenHistoricalMap/issues/issues/871
cc. @1ec5
> Fix transport lines layer

- images/tiler-server/config/providers/water_lines.toml
- images/tiler-server/config/providers/water_lines.zoom.toml
From: https://github.com/OpenHistoricalMap/issues/issues/869#issuecomment-2308986482
cc. @1ec5
> Fix water lines in vtiles

- images/tiler-server/config/providers/water_lines.toml
From: https://github.com/OpenHistoricalMap/issues/issues/869#issuecomment-2308986482
> Fix water lines  layer

- images/tiler-server/config/providers/place_points.toml
From https://github.com/OpenHistoricalMap/issues/issues/868#issuecomment-2308534630
> Add sea in point_places layer

- .github/workflows/frontend-tasking-manager.yaml
@Rub21, please vet these changes before merging.
> Update a number of env variables.

- values.production.template.yaml
> Increase DB connections for production

- .github/workflows/chartpress.yaml
- .github/workflows/frontend-overpass.yaml
- images/web/liveness.sh
- images/web/start.sh
- ohm/requirements.yaml
- values.development.template.yaml
- values.production.template.yaml
- values.staging.template.yaml
- Health checker for PostgreSQL connection https://github.com/OpenHistoricalMap/issues/issues/886
- Restart rake job for mailer https://github.com/OpenHistoricalMap/issues/issues/899
- Update Docker container for minute replication and planet replication
- Add the container in a new pool of nodes https://github.com/OpenHistoricalMap/issues/issues/861#issuecomment-2418560476
- Update for  overpass-turbo.
cc. @danrademacher @1ec5 @erictheise
> Updates  for production

- ohm/requirements.yaml
from https://github.com/OpenHistoricalMap/issues/issues/904
> Set the working version for osmcha

- .github/workflows/frontend-overpass.yaml
- ohm/requirements.yaml
- values.production.template.yaml
- values.staging.template.yaml
- Disable osmcha in staging https://github.com/OpenHistoricalMap/issues/issues/904
- Update nominatim endpoint in overpass-turbo https://github.com/OpenHistoricalMap/issues/issues/887
cc. @1ec5 @danrademacher
> Update overpass - Nominatim API url

- .github/workflows/frontend-overpass.yaml
- ohm/requirements.yaml
- values.staging.template.yaml
- New release for overpass-turbo 
- Updating the templates for TM, to use ConfigMap for env vars
- 
cc . @danrademacher
> New release for overpass-turbo and TM templates

- images/web/Dockerfile
> Update map style  - production

- .github/workflows/chartpress.yaml
- images/web/Dockerfile
- ohm/requirements.yaml
- values.development.template.yaml
- values.production.template.yaml
- values.staging.template.yaml
From: 
- https://github.com/OpenHistoricalMap/issues/issues/848
- https://github.com/OpenHistoricalMap/issues/issues/843
- https://github.com/OpenHistoricalMap/issues/issues/575
This PR aims to detect corrupted files generated by Osmosis. There is no way to fix corrupted files in Osmosis, but we have developed a method to check for corrupted files. If any are detected, the files will be regenerated. The script in the minute replication container will check the gz files, and if any issues are detected, a message will be sent to Slack.
PR in osm-seed https://github.com/developmentseed/osm-seed/pull/348
cc. @danrademacher
> Detecting Corrupted  Minute replication 

- values.production.template.yaml
From:  https://github.com/OpenHistoricalMap/issues/issues/894
> Update node for api db

- values.production.template.yaml
> Increase  node size for tiler-db

- .github/workflows/frontend-overpass.yaml
- images/web/Dockerfile
- ohm/requirements.yaml
- values.production.template.yaml
- values.staging.template.yaml
- Update map style versions
- Time slider updates, currently this is working fine in staging release
- Release v2.1.1 of overpass-turbo
cc @danrademacher @erictheise
> Updates in OHM timeslider and overpass-turbo 

- images/tiler-cache/Dockerfile
- images/tiler-server/Dockerfile
- values.production.template.yaml
- values.staging.template.yaml
From : https://github.com/OpenHistoricalMap/issues/issues/923
Because tegola version v0.20. is having some issue seeding the tiles,  lets use v.0.19 https://github.com/go-spatial/tegola/issues/880#issuecomment-2541762655
> Downgrade the version to v0.19

- .github/workflows/chartpress.yaml
- images/tiler-imposm/config/layers/transport_lines.json
- images/tiler-imposm/start.sh
- images/tiler-server/config/providers/transport_lines.toml
- images/tiler-server/config/providers/transport_lines.zoom.toml
- values.production.template.yaml
- values.staging.template.yaml
From https://github.com/OpenHistoricalMap/issues/issues/923#issuecomment-2541708852
> Fix transport lines layer simplification 

- images/web/config/settings.local.yml
- images/web/config/settings.yml
- images/web/start.sh
> Update settings file in advance of upstream merge.

- images/web/Dockerfile
Update lates gitsha  for ohm-website
> Update ohm-website latest gitsha

- images/tiler-server/Dockerfile
- values.production.template.yaml
> Update OSMCha app version and Fix vtitles water_lines

- ohm/requirements.yaml
- values.production.template.yaml
> Add priorityClass for production pods and adjust nodes for other pods

- images/web/config/production.conf
From: https://github.com/OpenHistoricalMap/issues/issues/990
> Fix CORS for *.json files

- images/web/Dockerfile
Includes latest work from @1ec5 and translation updates.
> 20250326 ohm website

- images/web/Dockerfile
- images/web/config/production.conf
- images/web/start.sh
- values.staging.template.yaml
From: https://github.com/OpenHistoricalMap/issues/issues/992#issuecomment-2759138296
cc. @danrademacher @erictheise
> Temporary fix for map styles and the vtiles services that use them

- images/web/config/production.conf
- images/web/start.sh
cc. @danrademacher @erictheise
> Update apache config to point  dist folder for map-styles

- .github/workflows/frontend-overpass.yaml
From https://github.com/OpenHistoricalMap/issues/issues/1036
> Update map-style url for overpass-turbo frontend

- .github/workflows/frontend-tasking-manager.yaml
From https://github.com/OpenHistoricalMap/issues/issues/876
cc. @erictheise
> Update stats URL for Tasking Manager - frontend

- .github/workflows/chartpress.yaml
- hetzner/seed.sh
- hetzner/tiler.production.yml
- hetzner/tiler.staging.yml
- images/tiler-imposm/start.sh
From: https://github.com/OpenHistoricalMap/issues/issues/1043
> Update date format for starting the IMPOSM job update

- ohm/requirements.yaml
From https://developmentseed.slack.com/archives/CACTQ7MU4/p1747257808055569
osm-seed PR: https://github.com/developmentseed/osm-seed/pull/365
> Fix vtiles endpoint for external IPs - osm-seed

- images/web/Dockerfile
- images/web/config/settings.yml
- images/web/start.sh
Eric opened a PR  about map-style, it should go first to staging  and then to production, https://github.com/OpenHistoricalMap/ohm-deploy/pull/545. 
cc. @danrademacher @1ec5 @erictheise
>  Week 24 Production Release - MapStyle updates v.0.9.8 - Use osm.org as identity provider

- images/tiler-cache/config.py
- images/tiler-cache/sqs_processor.py
From: https://github.com/OpenHistoricalMap/issues/issues/1080
> Enable delayed cleanup for tiler cache - by default 1 hour

- ohm/requirements.yaml
From https://github.com/developmentseed/osm-seed/pull/369
cc. @1ec5
> osm-seed version update

- .github/workflows/frontend-tasking-manager.yaml
Re: https://github.com/OpenHistoricalMap/issues/issues/1093 and https://github.com/OpenHistoricalMap/issues/issues/1092.
> : upstream …catchup to pull in security fix

- .github/workflows/frontend-tasking-manager.yaml
Re: https://github.com/OpenHistoricalMap/issues/issues/1093
> Set stats url to production

- .github/workflows/deploy-nominatim.yaml
- .github/workflows/deploy-overpass.yaml
- .gitignore
- hetzner/nominatim/nominatim.production.yml
- hetzner/nominatim/nominatim.staging.yml
- hetzner/overpass/overpass.production.yml
- hetzner/overpass/overpass.staging.yml
From https://github.com/OpenHistoricalMap/issues/issues/1084
> GA to deploy nominatim and Overpass

- .github/workflows/chartpress.yaml
- .github/workflows/deploy-nominatim.yaml
- .github/workflows/deploy-overpass.yaml
- .github/workflows/frontend-overpass.yaml
- hetzner/README.md
- hetzner/nominatim/nominatim.production.yml
- hetzner/nominatim/nominatim.staging.yml
- hetzner/overpass/overpass.production.yml
- hetzner/overpass/overpass.staging.yml
- hetzner/tiler.production.yml
- hetzner/tiler.staging.yml
- images/tasking-manager-api/Dockerfile
- images/tasking-manager-api/pyproject.toml
- ohm/requirements.yaml
- values.production.template.yaml
- values.staging.template.yaml
From: https://github.com/OpenHistoricalMap/issues/issues/1084 and https://github.com/developmentseed/osm-seed/pull/371
> Week 31 Production release -  Nominatim and Overpass migration

- hetzner/README.md
- hetzner/nominatim/nominatim.production.yml
- hetzner/nominatim/nominatim.staging.yml
- hetzner/overpass/overpass.production.yml
- hetzner/overpass/overpass.staging.yml
- images/web/Dockerfile
- images/web/config/production.conf
- ohm/requirements.yaml
- values.production.template.yaml
- values.staging.template.yaml
From: https://github.com/OpenHistoricalMap/ohm-deploy/pull/587
> Fix migration for nominatim and overpass

- .github/workflows/chartpress.yaml
- hetzner/ohmx_adiff/ohmx_adiff.staging.yml
- hetzner/seed.sh
- hetzner/tiler.production.yml
- hetzner/tiler.staging.yml
- images/tiler-imposm/queries/ohm_mviews/admin_boundaries_areas.sql
- images/tiler-imposm/scripts/create_mviews.sh
- images/tiler-imposm/scripts/refresh_mviews.sh
- images/tiler-server/config/config.template.toml
- images/tiler-server/config/providers/admin_boundaries_polygon.toml
- images/tiler-server/scripts/build_config.py
- images/tiler-server/start.sh
From: https://github.com/OpenHistoricalMap/issues/issues/1096
This change adds a new provider containing the OHM admin boundaries in polygons; it does not interfere with our current vector tiles or performance.
> Tiler admin boundaries areas
