OpenHistoricalMap/ohm-deploy

values.production.template.yaml

ref https://github.com/OpenHistoricalMap/issues/issues/261
@Rub21 @batpad @danrademacher @jeffreyameyer it looks like the replication process didn't create sequence number 451151 (`/000/451/151.osc.gz`). From what I can tell this is just a blip and likely doesn't have any features in the replication. I can't be sure until we generate it manually. As it stands tiler updates have stopped since June 23. 
This PR will restart imposm with the next valid replication and allow to catchup.

make imposm skip replication 451151 

---

images/tiler-server/seed-by-diffs.sh
images/tiler-server/tile_cache_downloader.sh

From: https://github.com/OpenHistoricalMap/issues/issues/333#issuecomment-1055127984
We figured out that Tiler cache cleaner is creating a tons of logs that are storing in New relic, We are making some changes to avoid printing such logs in order to reduce  the workload in New relic. e.g of the logs👇 

Avoid printing  tiler cache logs

---

chartpress.yaml
images/tasking-manager-api/Dockerfile
images/tasking-manager-api/README.md
ohm/values.yaml

Adds the OHM fork for Tasking Manager to the ohm-deploy process. This should now build and deploy Tasking Manager from our fork.
@Rub21 does this look right?
cc @willemarcel

add tm container with ohm fork

---

ohm/requirements.yaml

@Rub21 I rebased your changes on `osm-seed` develop fixing the TM build, and published a new version of `osm-seed` from this branch: https://github.com/developmentseed/osm-seed/pull/254
That just includes the env var changes that should make `iD` and `memcached` work again on staging. If you need to make any further changes on `osm-seed`, could you branch off the `fix/osm-env-names` branch in `osm-seed`?

update osm-seed version (use version from fix/osm-env-names branch)

---

ohm/requirements.yaml

Attempting to fix https://github.com/OpenHistoricalMap/issues/issues/420
Sets the idle connection timeout value on the load balancer: https://github.com/developmentseed/osm-seed/pull/254/commits/0a6dc249eb750b9ab522389d9107eb8bde5d5a9d
It's a bit of a shot in the dark, but maybe worth trying.

use updated version of osm-seed setting connection timeout

---

images/db/Dockerfile

from: https://github.com/OpenHistoricalMap/issues/issues/484
According to the documentation: https://www.postgresql.org/message-id/Y2kmqL%2BpCuSZiQBV%40msg.df7cb.de
> Re: To PostgreSQL in Debian
> With the end of LTS support for Debian stretch, we are no longer
> supporting stretch on [apt.postgresql.org](http://apt.postgresql.org/).
> 
> https://wiki.debian.org/LTS/
> 
> stretch-pgdg has been copied to [apt-archive.postgresql.org](http://apt-archive.postgresql.org/) and will be
> removed from [apt.postgresql.org](http://apt.postgresql.org/) at the end of October 2022.
> The files have been removed now.
> If you still need stretch, the files are on apt-archive now:
I have updated the  source list.

Update Postgres list source 

---

values.production.template.yaml

Updating values for tiler, using this changes, we are going to reinsert the data into a clean tiler database.
The issue happens  because, when we updated the changes 3 days ago, the data insertion was not restarted for tiler, there were some changes in the tiler that needs re-insert data  into a new tiler DB : e.g: https://github.com/OpenHistoricalMap/issues/issues/463 , and some other changes that there is not necessary to re-insert the data. e.g: https://github.com/OpenHistoricalMap/issues/issues/111

Update replication values for production tiler

---

values.production.template.yaml

From : https://github.com/OpenHistoricalMap/issues/issues/509
@batpad , I've updated the  OHM subdomain for TM,  these env vars are going to pass to the backend,  for the front-end need to be updated here:https://github.com/OpenHistoricalMap/tasking-manager/settings/secrets/actions, which i already updated. 
Note:
These changes are directly to production, since  this is not  code changes and also we are testing the new version of the website in staging. 
cc. @danrademacher

Update OHM's subdomain in tasking manager

---

.github/workflows/frontend-nominatim.yaml
.github/workflows/frontend-overpass.yaml
images/web/Dockerfile

I have added some restrictions in github action config, to evade pushing static files in s3 in case building fails.

Avoid pushing files in s3 if build fails for static pages

---

.github/workflows/chartpress.yaml
.gitignore
ohm/requirements.yaml
values.production.template.yaml
values.staging.template.yaml

Here are the necessary changes for the production installation, this new version includes:
Update to Kubernetes 1.27
Autoscaling for both the web and tiler servers.
Autoscaling for cron job pods.
cc. @batpad @geohacker @danrademacher

Production installation in Kubernetes 1.27

---

values.production.template.yaml
values.staging.template.yaml

In the current situation, when we pass large numbers in Kubernetes templates (more that 6 digits), they are converted to scientific notation, which leads to issues with recognition, particularly for imposm. Therefore, it is better to pass such numbers as strings.
cc. @batpad

Pass sequence number as string for imposm

---

.github/workflows/frontend-overpass.yaml
images/web/Dockerfile

Update ohm-website - production

---

images/tiler-server/Dockerfile
images/tiler-server/cache_cleaner.sh
images/tiler-server/rm_tegola_ps.sh
ohm/requirements.yaml
values.production.template.yaml
values.staging.template.yaml

The following script is designed to remove processes that overload the `tiler-server-cache-cleaner`  container. This is especially relevant when the tegola process doesn't finish and spawns numerous processes due to extensive editing on the api-server. We manually eliminate the tegola processes and also clear the S3 cache by hand,  removing the exiting tiles in s3 in case all cache in tiler server. 

Remove tiler cache manually when container gets too busy.

---

.github/workflows/chartpress.yaml
images/db/Dockerfile
images/tasking-manager-api/Dockerfile
images/web/config/production.conf
ohm/requirements.yaml
values.production.template.yaml
values.staging.template.yaml

- Update cgimap config https://github.com/OpenHistoricalMap/issues/issues/629
- Multi backups config: https://github.com/OpenHistoricalMap/issues/issues/632
-  Update python version and dependencias for chartpress 
- Update OSM dependencies fro api-web db contianer
- Change from Alpine to Slim version as base image  for container for TM
cc. @batpad  @danrademacher

Update Apache  cgimap config and  config for db backups 

---

ohm/requirements.yaml
values.production.template.yaml
values.staging.template.yaml

From: https://github.com/OpenHistoricalMap/issues/issues/633
By default,  the shared memory size is 64 MB, pointing  to `/dev/shm`, I am adding 512 MB as shared memory size for production container ; let's see how that works. that should be enough to avoid the issue.
cc. @batpad @1ec5

Adding Shared memory for web container

---

images/web/Dockerfile

This pulls in latest changes on ohm-website, which are tested locally, but the Chartpress Build and Deploy action is failing.
When I look here it seems like we've not had a successful Chartpress completion since about 3 weeks ago:
https://github.com/OpenHistoricalMap/ohm-deploy/actions/workflows/chartpress.yaml
Not sure yet what is causing this issue. The errors in my first attempt show up here:
https://github.com/OpenHistoricalMap/ohm-deploy/actions/runs/7333787524/job/19969695540#step:7:5013
Something about `rake assets precompile`, though Rails is building fine locally.
I tried just rerunning it, in case it was a transient glitch, same outcome.

update mapstyle, move to MapLibre, update iD

---

images/web/config/settings.yml
ohm/requirements.yaml
values.staging.template.yaml

From: https://github.com/OpenHistoricalMap/issues/issues/673

Add embed_server_url

---

ohm/requirements.yaml

Add a CLI `python manage.py backfill_changesets $(date -d "yesterday" +%Y-%m-%d) $(date +%Y-%m-%d)` in the cronjob to run updates in case of missing changeset from the day before.
From: https://github.com/OpenHistoricalMap/issues/issues/712

Update osm-seed version - osmcha

---

.github/workflows/frontend-nominatim.yaml
.github/workflows/frontend-overpass.yaml
.github/workflows/frontend-tasking-manager.yaml
ohm/requirements.yaml
values.staging.template.yaml

From: https://github.com/OpenHistoricalMap/issues/issues/725
Her is the configuration  for removing classic ELB and start using ingress-nginx  which  will reduce the cost from ELB in AWS. 
cc. @batpad @danrademacher @jeffreyameyer

Config for ingress-nginx  

---

images/web/config/settings.yml
values.production.template.yaml
values.staging.template.yaml

From https://github.com/OpenHistoricalMap/issues/issues/503
cc @danrademacher @erictheise

Support email updates

---

images/tiler-server/config/config.template.toml

It seems the transport lines from relations are causing some issues https://github.com/OpenHistoricalMap/issues/issues/761#issuecomment-2073900273. I am going to disable them for now, since there are no official styles for it. https://github.com/OpenHistoricalMap/issues/issues/761#issuecomment-2063964407
cc. @1ec5 @vknoppkewetzel

Disable Transport lines from relations - vtiles

---

images/db/config/postgresql.production.conf

From: https://github.com/OpenHistoricalMap/issues/issues/783
Production Database have  memory: "10Gi" and   cpu: "5" https://github.com/OpenHistoricalMap/ohm-deploy/blob/main/values.production.template.yaml#L75-L82 , According to it i set up the values similar to David's comment https://github.com/OpenHistoricalMap/issues/issues/783#issuecomment-2147878284 
cc. @batpad @bitner @danrademacher

Update values for api-db production

---

values.production.template.yaml
values.staging.template.yaml

cc. @batpad @danrademacher @jeffreyameyer

EBS Migration  to IO2 family disk for production DB

---

images/web/Dockerfile

Addresses https://github.com/OpenHistoricalMap/issues/issues/845 by deploying w/new iD build and a variety of small fixes to ohm-website.

For #845/Pull latest iD into website for staging deploy

---

images/tiler-server/start.sh
ohm/requirements.yaml
values.production.template.yaml

There is an issue when with the tiler server starting. 
```sh
SET
ERROR:  VACUUM cannot run inside a transaction block
CONTEXT:  SQL statement "VACUUM spatial_ref_sys"
PL/pgSQL function inline_code_block line 1 at EXECUTE
```
The VACUUM and ANALYZE process has not been running properly. for the tables because  of the above error Therefore, the rule is: every time a tiler server starts, we need to run VACUUM and ANALYZE to optimize the database tables. so i have updated the script .
cc. @1ec5

Fix issues VACUUM and ANALYZE  in tiler server

---

images/web/Dockerfile

These versions of the styles have been tested separately with the timeslider and embed and caused no errors in either one.

Update map style versions

---

images/tiler-cache/purge.py
images/tiler-cache/seed.py
images/tiler-server/purge_and_seed.sh
ohm/templates/tiler-cache-purge/deployment.yaml
values.production.template.yaml
values.staging.template.yaml

Because of the huge workload in seeding tiles, we need to reduce different zoom levels for purging and seeding.

Set zoom levels for Purge and Seed 

---

images/web/Dockerfile
images/web/start.sh
values.production.template.yaml

- From: https://github.com/OpenHistoricalMap/issues/issues/910#issuecomment-2529869796 , 
@danrademacher, the time-slider files (JS, CSS) and images have been copied during the build process in the web container. Could you take a look to ensure it is working as expected: https://staging.openhistoricalmap.org/?
Other changes in the PR:
- Update comment for start.sh in the web continaer
- Update concurrency and area for seeding vector tiles.

Copying Timeslider during the build process

---

images/tiler-imposm/start.sh
values.production.template.yaml

I am going to change the host for the Tiler database to AWS, since the issue ARM65 Hetzner still still affect the performance for imposm.
cc. @1ec5 @danrademacher @batpad @jeffreyameyer

Change db tiler host to AWS

---

images/cgimap/Dockerfile
images/web/Dockerfile
images/web/config/production.conf
images/web/config/settings.yml
ohm/requirements.yaml
values.production.template.yaml
values.staging.template.yaml

- Release new iD version
- Update license for xml outputs, rails/cgimap https://github.com/OpenHistoricalMap/issues/issues/448#issuecomment-2769291256
- Map-style redirects. https://github.com/OpenHistoricalMap/issues/issues/1005
cc. @danrademacher @erictheise @1ec5

Release iD 2.29.3,  license update and map-styles redirects

---

.github/workflows/chartpress.yaml
.gitignore
images/cgimap/Dockerfile
images/cgimap/liveness.sh
images/cgimap/start.sh
images/web/Dockerfile
images/web/config/production.conf
images/web/liveness.sh
images/web/start.sh
ohm/requirements.yaml
values.staging.template.yaml

From: https://github.com/OpenHistoricalMap/issues/issues/997 and https://github.com/OpenHistoricalMap/issues/issues/791
This PR splits the web and cgimap into different containers. This is because it’s better to handle these processes separately and keep the web container lighter, allowing services to start faster under high user concurrency.

Run web and cgimap processes  in different containers 

---

images/web/Dockerfile
images/web/start.sh

This PR includes the following updates:
- The gitsha for the ohm-website repository has been updated from staging branch
- A script section was added to replace the production vector tile URLs (vtiles) with the staging ones. This is necessary because the map style JSON files include production URLs by default, which caused staging deployments to still load tiles from production.
cc. @1ec5 @danrademacher

Hotfix: Week 24 – Update ohm-website production release

---

hetzner/README.md
hetzner/tiler.production.yml
hetzner/tiler.staging.yml

This PR only updates the Docker images for Hetzner and the README.

Update docker image for tiler-cache and imposm - hetzner config

---

images/web/config/settings.yml

As a followup to #561, each e-mail we send out needs to have a bogus e-mail address in the From: header too, not just Reply-To:.
Fixes OpenHistoricalMap/issues#1001.

Set e-mail sender to noreply
